### ISSUE TITLE
Not working for Unraid 6.12.11

### ISSUE THREAD

**Issue by ap-wtioit** [dlandon/python3#1]
Is the plugin not supported or was the assumption that 6.12.10 is the last 6ish release of unraid?

**Comment by dlandon** [comment]
This plugin is deprecated.

**Comment by kubedzero** [comment]
This plugin still shows up in Community Apps, is that correct if it's deprecated? It could also be helpful to archive this repository to really drive the point home.

For reference, I have the latest Python, 3.12.5, compiled for Unraid 6.12.13 and available at https://forums.unraid.net/topic/142908-python-311-unraid-txz-packageplugin/?do=findComment&comment=1458156
